name: CI/CD

on:
  pull_request:
    branches: [ "main" ]

env:
  DATABASE_USER: postgres
  DATABASE_PASS: postgres
  DATABASE_HOST: localhost
  DATABASE_PORT: 5432
  DATABASE_NAME: postgres
          
jobs:
  run-tests:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: pgvector/pgvector:pg16
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root

      - name: Run tests
        run: |
          make test
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: postgres
          AWS_S3_ENDPOINT_URL: https://revent-storage.s3.eu-west-1.amazonaws.com
          AWS_DEFAULT_REGION: us-west-1
          AWS_S3_BUCKET_NAME: revent-storage
          AWS_STORAGE_BUCKET_NAME: revent-media
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_QUERYSTRING_AUTH: False
          AWS_S3_SIGNATURE_VERSION: s3v4
