name: Resolve Issue with OpenHands

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]
  pull_request_review:
    types: [submitted]

permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  # call-openhands-resolver:
  #   uses: All-Hands-AI/OpenHands/.github/workflows/openhands-resolver.yml@main
  #   with:
  #     macro: ${{ vars.OPENHANDS_MACRO || '@openhands-agent' }}
  #     max_iterations: ${{ fromJson(vars.OPENHANDS_MAX_ITER || 50) }}
  #     base_container_image: ${{ vars.OPENHANDS_BASE_CONTAINER_IMAGE || '' }}
  #     LLM_MODEL: ${{ vars.LLM_MODEL || 'anthropic/claude-3-5-sonnet-20241022' }}
  #   secrets:
  #     PAT_TOKEN: ${{ secrets.PAT_TOKEN }}
  #     PAT_USERNAME: ${{ secrets.PAT_USERNAME }}
  #     LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
  #     LLM_BASE_URL: ${{ secrets.LLM_BASE_URL }}

  run-tests:
    # needs: call-openhands-resolver
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root

      - name: Run tests
        run: make test
        env:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres.atdcljqbnraswramrqkp
          POSTGRES_PASSWORD: J0rmUYg2M3y4EndR
          POSTGRES_HOST: aws-0-eu-central-1.pooler.supabase.com
          POSTGRES_PORT: 5432
          DJANGO_SETTINGS_MODULE: config.settings
          AWS_S3_ENDPOINT_URL: http://localhost.localstack.cloud:4566/
          AWS_DEFAULT_REGION: us-west-1
          AWS_S3_BUCKET_NAME: revent-storage
          AWS_STORAGE_BUCKET_NAME: revent-media
          AWS_ACCESS_KEY_ID: test
          AWS_SECRET_ACCESS_KEY: test
          AWS_QUERYSTRING_AUTH: False
          AWS_S3_SIGNATURE_VERSION: s3v4
          ALLOWED_HOSTS: localhost,127.0.0.1,0.0.0.0
          GOOGLE_CLIENT_ID: test
          GOOGLE_CLIENT_SECRET: test
          CSRF_TRUSTED_ORIGINS: http://localhost,http://localhost:3000,http://127.0.0.1:3000,http://127.0.0.1
          CORS_ALLOWED_ORIGINS: http://localhost,http://localhost:3000,http://127.0.0.1:3000,http://127.0.0.1,http://127.0.0.1:3001
          CORS_ORIGIN_WHITELIST: 127.0.0.1
          ALLOWED_REDIRECT_URIS: http://localhost:3000,http://localhost/,http://127.0.0.1:3000
          BASE_BACKEND_URL: http://localhost:8000/
          BASE_APP_URL: http://localhost:3000/
